# Dockerfile
FROM node:21.1.0-alpine AS build

# Set the working directory
WORKDIR /src
# Copy package files and install dependencies
COPY package.json ./
RUN npm install
# Copy application files and build the production bundle
COPY . .
# Stage 2: Production
FROM build AS production

COPY --from=build /src/.next ./.next
COPY --from=build /src/node_modules ./node_modules
COPY --from=build /src/package.json ./package.json
COPY --from=build /src/public ./public

CMD npm start
