apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-persistent-storage
        emptyDir:
          sizeLimit: 500Mi
      containers:
        - name: mysql
          args:
            - mysqld
            - --lower_case_table_names=1
          image: mysql:8.0
          ports:
            - name: tcp
              protocol: TCP
              containerPort: 3306
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "java-crud"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
