import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button } from "../../components/Button";
import { Api } from "@/services/Api";

export default function Visualizar() {
    const [message, setMessage] = useState("");

    const router = useRouter();
    const [id] = useState(router.query.id);

    const [cliente, setCliente] = useState([]);

    const getCliente = async () => {
        if (id === undefined) { 
            setMessage("Erro: Cliente não encontrado");
            return
        }

        await Api.get("/clientes/" + id)
        .then((response) => {
          setCliente(response.data.cliente);
        }).catch((err) => {
          if (err.response){
            setMessage(err.response.data.message);
          } else {
            setMessage("Erro tente novamente mais tarde!");
          }
        });
    }

    useEffect(() => {
        getCliente();
    }, [id]);

    return (
        <>
        <Head>
            <title>Cadastro de Cliente</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <main>
                <Link href={"/"}>
                    <Button 
                        text="Listar"
                    />
                </Link>
                {" "}
                <Link href={"/cadastrar"}>
                    <Button 
                        text="Cadastrar"
                    />
                </Link>
                {" "}
                <Link href={`/editar/${cliente.id}`}>
                    <Button 
                    text="Editar"
                  />
                </Link>
                {" "}
             
                <h2>Dados do Cliente</h2>

                {message ? <p>{message}</p>:""}

                <span>ID: {cliente.id}</span><br />
                <span>Nome: {cliente.nome}</span><br />

            </main>
        </>
    );
}
