import Head from "next/head";
import { useState } from "react";
import Link from "next/link";
import { Button } from "../components/Button";
import { InputText } from "../components/InputText";
import { ServiceCreate } from "@/services/Cliente";

export default function Cadastrar() {
  const [data, setData] = useState({
    id: 0,
    nome: ''
  });

  const [message, setMessage] = useState("");

  const valueInput = (e) => setData({
    ...data, 
    [e.target.name]: e.target.value
  });

  const addCliente = async (e) => {
    e.preventDefault();

    const response = await ServiceCreate('/clientes', data);
    setMessage(response);

    if (response === "Cliente criado com sucesso") {
      setData({
        nome: ''
      })
    };
  };

  return (
    <>
      <Head>
        <title>Cadastro de Cliente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={"/"}>
          <Button 
            text="Listar"
          />
        </Link>

        <h2>Cadastrar Cliente</h2>

        {message ? <p>{message}</p>:""}

        <form onSubmit={addCliente}>
          <label htmlFor="Nome">Nome:</label>
          <InputText
            textValue={data.nome}
            name="nome"
            handleChange={valueInput}
            placeholder="Digite o nome" 
          />
          <br /><br />
          <Button 
            text="Enviar"
          />
          <br /><br />
        </form>
      </main>
    </>
  );
}
