---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
  labels:
    app: crud
spec:
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: crud
          image: marceloagmelo/crud-frontend:1.1.3
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name