import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button } from "../../components/Button";
import { InputText } from "../../components/InputText";
import { Api } from "@/services/Api";
import { ServiceUpdate } from "@/services/Cliente" 

export default function Editar() {
    const [message, setMessage] = useState("");

    const router = useRouter();
    const [id] = useState(router.query.id);

    const [cliente, setCliente] = useState({
        id: '',
        nome: ''
    });

    const getCliente = async () => {
        if (id === undefined) { 
            setMessage("Erro: Cliente não encontrado");
            return
        }

        await Api.get("/clientes/" + id)
        .then((response) => {
          setCliente(response.data.cliente);
        }).catch((err) => {
          if (err.response){
            setMessage(err.response.data.message);
          } else {
            setMessage("Erro tente novamente mais tarde!");
          }
        });
    }

    useEffect(() => {
        getCliente();
    }, [id]);

    const valueInput = (e) => setCliente({
        ...cliente, 
        [e.target.name]: e.target.value
    });

    const updateCliente = async (e) => {
      e.preventDefault();

      const response = await ServiceUpdate('/clientes/' + id, cliente);
      setMessage(response);
    }

    return (
        <>
        <Head>
            <title>Cadastro de Cliente</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <main>
                <Link href={"/"}>
                  <Button 
                    text="Listar"
                  />
                </Link>{" "}
                <Link href={`/visualizar/${cliente.id}`}>
                  <Button 
                    text="Visualizar"
                  />
                </Link>
                {" "}

                <h2>Editar Cliente</h2>

                {message ? <p>{message}</p>:""}

                <form onSubmit={updateCliente}>
                    <label htmlFor="Nome">Nome:</label>
                    <input type="hidden" name="id" value={cliente.id}/>
                    <InputText
                      textValue={cliente.nome}
                      name="nome"
                      handleChange={valueInput}
                      placeholder="Digite o nome" 
                    />
                    <br /><br />
                    <Button 
                      text="Enviar"
                    />
                    <br /><br />
                </form>

            </main>
        </>
    );
}
